openapi: 3.0.3
info:
  title: GitHubRepositories
  description: GitHubRepositories
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /repositories:
    get:
      tags:
        - repositories
      operationId: getRepositories
      summary: Get list of repositories of user which are not forks
      parameters:
        - in: query
          name: username
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetRepositoriesResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '406':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    GetRepositoriesResponse:
      type: object
      required:
        - repositories
      properties:
        repositries:
          type: array
          items:
            $ref: '#/components/schemas/Repository'

    Repository:
      type: object
      required:
        - name
        - ownerLogin
        - branches
      properties:
        name:
          type: string
        ownerLogin:
          type: string
        branches:
          type: array
          items:
            $ref: '#/components/schemas/Branch'

    Branch:
      type: object
      required:
        - name
        - latestCommitSHA
      properties:
        name:
          type: string
        latestCommitSHA:
          type: string

    ErrorResponse:
      type: object
      required:
        - status
        - Message
      properties:
        status:
          type: string
        Message:
          type: string